server:
  port: 8082
  context-path: /
  session:
    cookie:
      name: UISESSION


security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: ClientId
      clientSecret: secret
      accessTokenUri: http://localhost:8081/auth/oauth/token
      userAuthorizationUri: http://localhost:8081/auth/oauth/authorize
      #useCurrentUri: false
      #preEstablishedRedirectUri: http://localhost:8082/login
    resource:
      userInfoUri: http://localhost:8081/auth/rest/auth/principal


spring:
  application:
    name: daanee-app
  thymeleaf:
    cache: false
    


#eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8302/eureka/
#  instance:
#    hostname: localhost